query getShopDetails{
  shop {
    name
    brand{
      colors{
        primary{
          background
          foreground
        }
        secondary{
          background
          foreground
        }
      }
      coverImage{
        alt
        image{
          height
          url
          altText
        }
        previewImage{
          height
          url
          altText
        }
      }
      logo{
        alt
        image{
          height
          url
          altText
        }
        previewImage{
          height
          url
          altText
        }
      }
      slogan
      shortDescription
      squareLogo{
        alt
        image{
          height
          url
          altText
        }
        previewImage{
          height
          url
          altText
        }
      }
    }
    description
    primaryDomain{
      host
      url
    }
    paymentSettings{
      currencyCode
      acceptedCardBrands
      enabledPresentmentCurrencies
      supportedDigitalWallets
    }
  }
}

